// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../../test/mocks/usecase_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "challenge-backend-1/internal/entity"
	model "challenge-backend-1/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(db *gorm.DB, user *entity.User, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", db, user, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(db, user, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), db, user, email)
}

// MockUserProducer is a mock of UserProducer interface.
type MockUserProducer struct {
	ctrl     *gomock.Controller
	recorder *MockUserProducerMockRecorder
	isgomock struct{}
}

// MockUserProducerMockRecorder is the mock recorder for MockUserProducer.
type MockUserProducerMockRecorder struct {
	mock *MockUserProducer
}

// NewMockUserProducer creates a new mock instance.
func NewMockUserProducer(ctrl *gomock.Controller) *MockUserProducer {
	mock := &MockUserProducer{ctrl: ctrl}
	mock.recorder = &MockUserProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProducer) EXPECT() *MockUserProducerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockUserProducer) Send(event *model.UserEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockUserProducerMockRecorder) Send(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockUserProducer)(nil).Send), event)
}
